#!/usr/bin/env node

const fs = require('fs');
const message = fs.readFileSync(process.argv[2], 'utf8').trim();

// 长度必须大于20个字符
const COMMIT_MESSAGE_LIMIT_LENGTH = 10;
if (message.length < COMMIT_MESSAGE_LIMIT_LENGTH) {
  console.log('提交消息长度必须大于10个字符');
  process.exit(1);
}

// 必须符合以下格式feat|fix|docs|chore|refactor(模块名): 描述信息
const CODE_CONTRACT = /^(feat|fix|docs|chore|refactor)\(\S+\)?:\s\S+/;
if (!CODE_CONTRACT.test(message)) {
  console.log('提交消息必须符合格式：feat|fix|docs|chore|refactor(模块名): 描述信息');
  process.exit(1);
}
