kind: pipeline
type: docker
name: Gfx


clone:
  disable: true



steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: go
        path: /go
    settings:
      test: false
      compress: false

  - name: 文档
    image: ccr.ccs.tencentyun.com/dronestock/node
    settings:
      folder: doc

  - name: 部署
    image: ccr.ccs.tencentyun.com/dronestock/cos
    settings:
      folder: doc/dist
      secret_id:
        from_secret: secret_id_cos
      secret_key:
        from_secret: secret_key_cos
      base_url: https://gfx-1253228583.cos.ap-chengdu.myqcloud.com


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
